config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'categories/:id/buy'  => 'categories#buy',  as:  :buy
  get 'categories/:id/sell' => 'categories#sell', as: :sell
  
  resources :users
  resources :microposts
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :microposts, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories=Category.all
  end

  def show
    if !logged_in?
      store_location
      flash[:warning] = "Sign In/ Signup to access our leads"
      redirect_to login_path
    end
  	@category=Category.find(params[:id])
  	@posts=@category.microposts.paginate(page: params[:page])
  end

  def buy
  	@category=Category.find(params[:id])
  	@posts=@category.microposts.paginate(page: params[:page])
  	@buy = @posts.where(buysell: 'Buy')
  end

  def sell
  	@category=Category.find(params[:id])
  	@posts=@category.microposts.paginate(page: params[:page])
  	@sell = @posts.where(buysell: 'Sell')
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/buy.html.erb
<% provide(:title, 'Buying leads for ' + @category.name) %>
<div class="wrapper">
<div class="container">
<h1 class="headline">Buying Leads for <%= @category.name %></h1>
<% if !@posts.empty? %>
<div class="center">
  <div class="col-xs-12 col-sm-6 col-md-4 category-post">
    <%= link_to "Click for only sell leads", sell_path, class: "btn btn-default btn-lg" %>  
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4 category-post">
    <%= link_to "Post buy or sell leads now", new_micropost_path, class: "btn btn-action btn-lg" %> 
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4 category-post">
    <%= link_to "View all buy/sell leads ", category_path, class: "btn btn-default btn-lg" %> 
  </div>
</div>
<%else%>
 <div class="center">
  <div class="col-sm-6 category-post">
    <%= link_to "View Categories", categories_path, class: "btn btn-default btn-lg" %>  
  </div>
  <div class="col-sm-6 category-post">
    <%= link_to "Post new lead", new_micropost_path, class: "btn btn-action btn-lg" %> 
  </div>
 </div>
<%end%>

<ol class="microposts">
<% @buy.each do |micropost| %>
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user%>
  <span class="user"><%= link_to micropost.user.name, micropost.user, class: "action-button shadow animate red" %></span><span class="action-button shadow animate <%=micropost.buysell %>"> <%=micropost.buysell %></span>
  <br><br><br>
  <span class="title"><%= micropost.title %></span>
  <span class="content"><%= micropost.content %></span>
  <% if !micropost.amount.nil? %>
  <span class="offer">Offer Amount: $<%=micropost.amount %></span>
  <%else%>
  <span class="timestamp">Offer Amount: Not Specified</span>
  <%end%>
  <span class="timestamp">Contact me @ <%=micropost.contact_detail %> </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <span>
    <% if current_user?(micropost.user) || current_user.admin? %>
      <%= link_to "delete", micropost, class: "delete-button shadow animate", method: :delete,
                                       data: { confirm: "Do you want to delete this post"}  %>
    <% end %>
  </span>
</li>
<%end%>
</ol>

<%= will_paginate @buy %>
</div>
</div>

app/views/categories/index.html.erb
<% provide(:metacontent, "Categories for B2B sales leads, b2b marketing leads and business leads. Online B2B marketplace for best buying and selling leads.") %>

<% provide(:title, 'B2B trade leads categories | B2B Sales & buy leads lists') %>
<div class ="category-display">
<section class=" container-fluid services-block text-center">

<div id="block-head text-center"><h1> B2B Leads Categories</h1><span></span></div>
<h2 class="shadow"> Click on below business leads categories </h2>
<%if logged_in? %>
    <p><%= link_to "Post buying/selling lead now", new_micropost_path, class: "btn btn-action btn-lg" %> 
<%end%>
<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/1" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/fashion.png">Apparel &amp; Fashion Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/2" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/agriculture">Agriculture Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/3" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/automobile.png">Automobile Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/4" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/computer">Computer Hardware &amp; Software Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/5" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/consumer-electronics.png">Consumer Electronics Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/6" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/mobile.png">Mobile Phones Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/7" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/ee.png">Electronics &amp; Electrical Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/8" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/energy-power.png">Energy &amp; Power Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/9" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/food-beverage.png">Food &amp; Beverage Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/10" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/real-estate.png">Construction &amp; Real Estate Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/11" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/chemicals.png">Chemicals Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/6" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/leather.jpg">Leather &amp; Leather Products Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/13" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/business-service.png">Business Services Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/14" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/hometextile.jpg">Home Textiles &amp; Furnishings Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/15" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/fabric.jpg">Textile &amp; Fabrics Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/16" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/mineral.svg">Minerals &amp; Metals Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/17" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/construction_industries.png">Industrial Supplies Leads</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/18" target="_blank"><div class="services-image"><img class="img-responsive" src="assets/health_beauty_icon.png	">Health &amp; Beauty Leads</div></a>
</div>

</section>
</div>

app/views/categories/index_old.html.erb
<!--<% @categories.each do |category| %>
<li>
  <span class="user"><%= link_to category.name, category %></span>
</li>
<%end%>
-->

<div class ="category-display">
<section class=" container-fluid services-block text-center">

<div id="block-head text-center"><h1> Categories</h1><span></span></div>
<h2 class="shadow"> Click on below categories for exciting deals </h2>
<%if logged_in? %>
    <p><%= link_to "Post buy/sell deal now", new_micropost_path, class: "btn btn-action btn-lg" %> 
<%end%>
<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/1" target="_blank"><div class="services-image"><img class="img-responsive" src="http://img.tradeindia.com/new_website1/ti-homepage-ver4/products-categories/apparel-fashion.png">Apparel &amp; Fashion</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/2" target="_blank"><div class="services-image"><img class="img-responsive" src="http://img.tradeindia.com/new_website1/ti-homepage-ver4/products-categories/agriculture.png">Agriculture</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/3" target="_blank"><div class="services-image"><img class="img-responsive" src="http://img.tradeindia.com/new_website1/ti-homepage-ver4/products-categories/automobile.png">Automobile</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/4" target="_blank"><div class="services-image"><img class="img-responsive" src="http://img.tradeindia.com/new_website1/ti-homepage-ver4/products-categories/computer-hardware-software.png">Computer Hardware &amp; Software</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/5" target="_blank"><div class="services-image"><img class="img-responsive" src="http://img.tradeindia.com/new_website1/ti-homepage-ver4/products-categories/consumer-electronics.png">Consumer Electronics</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/6" target="_blank"><div class="services-image"><img class="img-responsive" src="https://d30y9cdsu7xlg0.cloudfront.net/png/29541-200.png">Mobile Phones</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/7" target="_blank"><div class="services-image"><img class="img-responsive" src="http://img.tradeindia.com/new_website1/ti-homepage-ver4/products-categories/electronics-electrical-supplies.png">Electronics &amp; Electrical</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/8" target="_blank"><div class="services-image"><img class="img-responsive" src="http://img.tradeindia.com/new_website1/ti-homepage-ver4/products-categories/energy-power.png">Energy &amp; Power</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/9" target="_blank"><div class="services-image"><img class="img-responsive" src="http://img.tradeindia.com/new_website1/ti-homepage-ver4/products-categories/food-beverage.png">Food &amp; Beverage</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/10" target="_blank"><div class="services-image"><img class="img-responsive" src="http://img.tradeindia.com/new_website1/ti-homepage-ver4/products-categories/construction-real-estate.png">Construction &amp; Real Estate</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/11" target="_blank"><div class="services-image"><img class="img-responsive" src="http://www.calgoncarbon.com/wp-content/uploads/2015/03/Icon-BioBasedChemicals.png">Chemicals</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/6" target="_blank"><div class="services-image"><img class="img-responsive" src="https://e.ridersdiscount.com/generated/478/1/50478-black-river-road-vandal-leather-vest-2013_260.jpg">Leather &amp; Leather Products</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/13" target="_blank"><div class="services-image"><img class="img-responsive" src="http://cdn0.capterra-static.com/assets/images/hubpages/survey-report/report-handshake-icon.png">Business Services</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/14" target="_blank"><div class="services-image"><img class="img-responsive" src="https://images-na.ssl-images-amazon.com/images/I/71l1K-DC8VL._SL1000_.jpg">Home Textiles &amp; Furnishings</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/15" target="_blank"><div class="services-image"><img class="img-responsive" src="http://2.imimg.com/data2/AB/FT/MY-2316978/cotton-fabric-250x250.jpg">Textile &amp; Fabrics</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/16" target="_blank"><div class="services-image"><img class="img-responsive" src="http://georesonance.com/img/icon_mineral_exploration.svg">Minerals &amp; Metals</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/17" target="_blank"><div class="services-image"><img class="img-responsive" src="http://cubez.ae/images/construction_industries.png">Industrial Supplies</div></a>
</div>

<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 services">
<a href="/categories/18" target="_blank"><div class="services-image"><img class="img-responsive" src="http://s3.amazonaws.com/saveoneverything_assets/assets/images/icons/health_beauty_icon.png">Health &amp; Beauty</div></a>
</div>

</section>
</div>

app/views/categories/sell.html.erb
<% provide(:title, 'Sale leads for ' + @category.name) %>
<div class = "wrapper">
<div class="container">
<h1 class="headline">Selling leads for <%= @category.name %></h1>
<% if !@posts.empty? %>
<div class="center">
  <div class="col-xs-12 col-sm-6 col-md-4 category-post">
    <%= link_to "Click for all buying leads", buy_path, class: "btn btn-default btn-lg" %>  
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4 category-post">
    <%= link_to "Post buy or sell lead now", new_micropost_path, class: "btn btn-action btn-lg" %> 
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4 category-post">
    <%= link_to "View all buy/sell leads ", category_path, class: "btn btn-default btn-lg" %> 
  </div>
</div>
<%else%>
 <div class="center">
  <div class="col-sm-6 category-post">
    <%= link_to "View Categories", categories_path, class: "btn btn-default btn-lg" %>  
  </div>
  <div class="col-sm-6 category-post">
    <%= link_to "Post new lead", new_micropost_path, class: "btn btn-action btn-lg" %> 
  </div>
 </div>
<%end%>

<ol class="microposts">
<% @sell.each do |micropost| %>
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user%>
  <span class="user"><%= link_to micropost.user.name, micropost.user, class: "action-button shadow animate red" %></span><span class="action-button shadow animate <%=micropost.buysell %>"> <%=micropost.buysell %></span>
  <br><br><br>
  <span class="title"><%= micropost.title %></span>
  <span class="content"><%= micropost.content %></span>
  <% if !micropost.amount.nil? %>
  <span class="offer">Offer Amount: $<%=micropost.amount %></span>
  <%else%>
  <span class="timestamp">Offer Amount: Not Specified</span>
  <%end%>
  <span class="timestamp">Contact me @ <%=micropost.contact_detail %> </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <span>
    <% if current_user?(micropost.user) || current_user.admin? %>
      <%= link_to "delete", micropost, class: "delete-button shadow animate", method: :delete,
                                       data: { confirm: "Do you want to delete this post"}  %>
    <% end %>
  </span>
</li>
<%end%>
</ol>

<%= will_paginate @sell %>
</div>
</div>

app/views/categories/show.html.erb
<% provide(:metacontent, 'We provide free trade and marketing leads for ' + @category.name ) %>
<% provide(:title, @category.name + ' sales & trade leads') %>
<div class="wrapper">
<div class="container">
<h1 class="headline">Posts for <%= @category.name %></h1>

<% if !@posts.empty? %>
<div class="center">
  <div class="col-xs-12 col-sm-6 col-md-4 category-post">
    <%= link_to "Only buy leads", buy_path, class: "btn btn-default btn-lg" %>  
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4 category-post">
    <%= link_to "Post new lead", new_micropost_path, class: "btn btn-action btn-lg" %> 
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4 category-post">
    <%= link_to "Only sell leads", sell_path, class: "btn btn-default btn-lg" %> 
  </div>
</div>
<%else%>
 <div class="center">
  <div class="col-sm-6 category-post">
    <%= link_to "View Categories", categories_path, class: "btn btn-default btn-lg" %>  
  </div>
  <div class="col-sm-6 category-post">
    <%= link_to "Post new leads", new_micropost_path, class: "btn btn-action btn-lg" %> 
  </div>
 </div>
<%end%>

<ol class="microposts">

<% @posts.each do |micropost| %>
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user%>
  <span class="user"><%= link_to micropost.user.name, micropost.user, class: "action-button shadow animate red" %></span>
  <% if micropost.buysell == "Buy" %>
  <span> <%= link_to micropost.buysell, buy_path, class: "action-button shadow animate Sell" %></span>
  <%else%>
  <span> <%= link_to micropost.buysell, sell_path, class: "action-button shadow animate Buy" %></span>
  <%end%>
  <!-- <span class="action-button shadow animate <%=micropost.buysell %>"> <%=micropost.buysell %></span>  -->
  <br><br><br>
  <span class="title"><%= micropost.title %></span>
  <span class="content"><%= micropost.content %></span>
  <% if !micropost.amount.nil? %>
  <span class="offer">Offer Amount: $<%=micropost.amount %></span>
  <%else%>
  <span class="timestamp">Offer Amount: Not Specified</span>
  <%end%>
  <span class="timestamp">Contact me @ <%=micropost.contact_detail %> </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <span>
    <% if current_user?(micropost.user) || current_user.admin? %>
      <%= link_to "delete", micropost, class: "delete-button shadow animate", method: :delete,
                                       data: { confirm: "Do you want to delete this post"}  %>
    <% end %>
  </span>
</li>
<%end%>

</ol>

<%= will_paginate @posts %>
</div>
</div>
<% if @posts.empty? %>
  <h2 class="shadow" style="color: #000"> All deals under this category are now over. New deals coming soon! </h2>
<%end%>