config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'categories/:id/buy'  => 'categories#buy',  as:  :buy
  get 'categories/:id/sell' => 'categories#sell', as: :sell
  
  resources :users
  resources :microposts
  resources :categories

end

app/views/layouts/_footer.html.erb
<div style="background: #282828">
<div class="container">
<footer class="footer one">
  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4"><h3>More about company</h3>
      <div>
          <p> Trade India Leads is an online B2B marketplace for providing its users a unique and simple solution for there business needs. Spanned across 18 business categories we give buyers and sellers an excellent opportunity to use our B2B platform for posting and viewing b2b sales, b2b marketing and b2b trade leads for free. Join us and start posting your buying and selling leads.</p>
      </div>
  </div>
  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4"><h3>Facebook (Follow us)</h3>
      <div>
            <a href="https://www.facebook.com/India-Leads-1723995611193151/?ref=br_rs" target="_blank" ><img src="http://wapkaimage.com/400723/400723469_4b4c6767c9.gif"><i></i>                Like us on Facebook</a>
      </div>
  </div>
  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4"><h3>Contact Information </h3>
        <div class="footer three">
          <ul>
            <li>Trade India Leads <span>New Delhi,</span> India  </li>
            <li>+91-7000277265  </li>
            <li><a href="mailto:tiloffers@gmail.com">tiloffers@gmail.com</a> </li>
          </ul>
        </div>
  </div>
</footer>
</div>
</div>

app/views/layouts/_header.html.erb
  <!-- Fixed navbar -->
  <div class="navbar navbar-inverse navbar-fixed-top headroom" >
    <div class="container">
      <div class="navbar-header">
        <!-- Button for smallest screens -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        <!-- <a class="navbar-brand" href="index.html"><img src="assets/images/logo.png" alt="Progressus HTML5 template"></a> -->
        <%= link_to image_tag('logo.png', alt: "Topdeals"), root_path, class: "navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Categories", categories_path %></li>
          <li><%= link_to "About Us", about_path %></li>
          <% if logged_in? %>
              <li><%= link_to "Post Lead", new_micropost_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                 <li><%= link_to "Profile", current_user %></li>
                 <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                 <li class="divider"></li>
                 <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                 </li>
                </ul>
              </li>
        <% else %>
              <li><%= link_to "Signup", signup_path %></li>
              <li><%= link_to "Log in", login_path, class: "btn" %></li>
        <% end %>

<!--               <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">More Pages <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Left Sidebar</a></li>
                  <li class="active"><a href="sidebar-right.html">Right Sidebar</a></li>
                </ul>
              </li>
          <li><a href="#">Contact</a></li>
          <li><a class="btn" href="#">SIGN IN / SIGN UP</a></li> -->
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Mr+Dafoe' rel='stylesheet' type='text/css'>
  <%= render 'layouts/shim' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="<%= yield(:metacontent)%>" >
  <meta name="keywords" content="TradeIndia Leads, business leads, sales offer, B2B marketing, export, import, marketing leads, business leads, top sales offer, overstock, business networking">
  <meta name="author" content="">
  <meta name="google-site-verification" content="oxCfN2-A2gAu0vaSdBgcjg2Nnt9XwJ0RniAdf3U-8zg" />
</head>
<body>
    <%= render 'layouts/header' %>
    <div>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>